### ISSUE TITLE
    [SoapFault] Error Fetching http headers

### ISSUE THREAD

**Issue by ghost** [fferreri/netsuite-data-dumper#1]
I'm getting the following randomly. I've tried different page sizes. Sometimes it runs for 10 minutes sometimes just 30 seconds. I've tried PHP 5.5 and 7.x same problem. Increased socket timeout to 600. Anything else to try?

thank you

Exception trace:
 () at /mnt/hd/NetsuiteBackup/netsuite-data-dumper/vendor/fungku/netsuite-php/src/NetSuiteClient.php:234
 SoapClient->__doRequest() at n/a:n/a
 SoapClient->__soapCall() at /mnt/hd/NetsuiteBackup/netsuite-data-dumper/vendor/fungku/netsuite-php/src/NetSuiteClient.php:234
 Fungku\NetSuite\NetSuiteClient->makeSoapCall() at /mnt/hd/NetsuiteBackup/netsuite-data-dumper/vendor/fungku/netsuite-php/src/NetSuiteService.php:186
 Fungku\NetSuite\NetSuiteService->searchMoreWithId() at /mnt/hd/NetsuiteBackup/netsuite-data-dumper/src/Commands/GetRecordsCommand.php:161
 FFerreri\Commands\GetRecordsCommand->execute() at /mnt/hd/NetsuiteBackup/netsuite-data-dumper/vendor/symfony/console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at /mnt/hd/NetsuiteBackup/netsuite-data-dumper/src/Commands/DumpAllCommand.php:66
 FFerreri\Commands\DumpAllCommand->execute() at /mnt/hd/NetsuiteBackup/netsuite-data-dumper/vendor/symfony/console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at /mnt/hd/NetsuiteBackup/netsuite-data-dumper/vendor/symfony/console/Application.php:878
 Symfony\Component\Console\Application->doRunCommand() at /mnt/hd/NetsuiteBackup/netsuite-data-dumper/vendor/symfony/console/Application.php:195
 Symfony\Component\Console\Application->doRun() at /mnt/hd/NetsuiteBackup/netsuite-data-dumper/vendor/symfony/console/Application.php:126
 Symfony\Component\Console\Application->run() at /mnt/hd/NetsuiteBackup/netsuite-data-dumper/dumper.php:31

**Comment by ghost** [comment]
I was able to figure this out. Haven't had any issues, been running for hours.

I changed the following file int two places:

vendor/fungku/netsuite-php/src/NetSuiteClient.php

Line 64:
        **$options['connection_timeout'] = 60;**

Line 69:
        **$options['keep_alive'] = true;**

**Comment by fferreri** [comment]
Thanks for sharing your fix!
